### ISSUE TITLE
run_tests.py fails if scipy is not installed

### ISSUE THREAD

**Issue by cdeil** [b45ch1/algopy#35]
Can you change run_tests.py so that it works even if scipy is not available?

```
$ python run_tests.py 
Traceback (most recent call last):
  File "run_tests.py", line 1, in <module>
    from algopy.tracer.tests.test_tracer import *
  File "/home/deil/software/algopy/algopy/__init__.py", line 66, in <module>
    import utpm
  File "/home/deil/software/algopy/algopy/utpm/__init__.py", line 29, in <module>
    from utpm import *
  File "/home/deil/software/algopy/algopy/utpm/utpm.py", line 18, in <module>
    from algorithms import RawAlgorithmsMixIn, broadcast_arrays_shape
  File "/home/deil/software/algopy/algopy/utpm/algorithms.py", line 34, in <module>
    from algopy import nthderiv
  File "/home/deil/software/algopy/algopy/nthderiv/__init__.py", line 5, in <module>
    from nthderiv import *
  File "/home/deil/software/algopy/algopy/nthderiv/nthderiv.py", line 339, in <module>
    @basecase(scipy.special.hyperu, domain=DOM_POS, extras=2)
AttributeError: 'NoneType' object has no attribute 'special'
[deil@localhost algopy]$ python -c 'import numpy'
[deil@localhost algopy]$ python -c 'import scipy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named scipy
```

**Comment by b45ch1** [comment]
Closing due to inactivity.
