### ISSUE TITLE
Support for fancy indexing

### ISSUE THREAD

**Issue by dpo** [b45ch1/algopy#47]
Currently, Algopy doesn't appear to support fancy indexing. Here is a simple example:

``` python
import algopy
import numpy as np

indices = [0,2]
rhs = np.array([4., 1.])

def c(x):
    "Represent the system c(x)-rhs = 0."
    cx = algopy.zeros(3, dtype=x)
    cx[0] = (1 + x[0]**2)**2 + x[1]**2
    cx[1] = algopy.sum(x)
    cx[2] = x[0] - x[1]**2
    cx[indices] -= rhs
    return cx

x0 = 2 * np.ones(2)
cg = algopy.CGraph()
x = algopy.Function(x0)
y = c(x)
cg.trace_off()
cg.independentFunctionList = [x]
cg.dependentFunctionList = [y]
print cg.jacobian(x0)
```

Curently, running the above script results in

``` python
Traceback (most recent call last):
  File "test_algopy.py", line 23, in <module>
    print cg.jacobian(x0)
  File "/Users/dpo/.virtualenvs/nlpy3/lib/python2.7/site-packages/algopy/tracer/tracer.py", line 357, in jacobian
    self.pushforward(utpm_x_list)
  File "/Users/dpo/.virtualenvs/nlpy3/lib/python2.7/site-packages/algopy/tracer/tracer.py", line 112, in pushforward
    raise Exception(err_str)
Exception: pushforward of node 18 failed (getitem)reported error is:
too many indicestraceback:
Traceback (most recent call last):
  File "/Users/dpo/.virtualenvs/nlpy3/lib/python2.7/site-packages/algopy/tracer/tracer.py", line 106, in pushforward
    f.__class__.pushforward(f.func, f.args, Fout = f)
  File "/Users/dpo/.virtualenvs/nlpy3/lib/python2.7/site-packages/algopy/tracer/tracer.py", line 807, in pushforward
    out  = func(*args)
  File "/Users/dpo/.virtualenvs/nlpy3/lib/python2.7/site-packages/algopy/utpm/utpm.py", line 137, in __getitem__
    tmp = self.data.__getitem__((slice(None),slice(None)) + tuple(sl))
IndexError: too many indices
```

**Comment by b45ch1** [comment]
Closing due to inactivity.
